### ISSUE TITLE
ENTITY_ERROR.ATTRIBUTE.REQUIRED when notarizing

### ISSUE THREAD

**Issue by soundasleep** [devbotsxyz/xcode-notarize#10]
I'm brand new to this confusing world of notarizing apps and I'm getting the following error in my build:

```yml
    - name: "Notarize Release Build"
      uses: actions/notarization-action@v1
      with:
        product-path: ${{ github.workspace }}/desktop/build/package/DesktopLauncher.dmg
        appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}   # e.g. foo@example.com
        appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}   # e.g. app-specific password
        verbose: true
```

Output results:

```
Run devbotsxyz/xcode-notarize@v1
  with:
    product-path: /xxx/desktop/build/package/DesktopLauncher.dmg
    appstore-connect-username: ***
    appstore-connect-password: ***
    verbose: false
  env:
    JAVA_HOME: /xxx
    PATH: /xxx
Archiving Application
  Created application archive at /tmp/archive.zip
Submitting for Notarizing
  Error: -19208 - You must provide a value for the attribute 'bundle' with this request With error code ENTITY_ERROR.ATTRIBUTE.REQUIRED for id xxxx-xxxx-xxxx
```

Any ideas?

**Comment by soundasleep** [comment]
It seems passing in an explicit `primary-bundle-id` helped:

```yml
    - name: "Notarize Release Build"
      uses: devbotsxyz/xcode-notarize@v1
      with:
        product-path: ${{ github.workspace }}/desktop/build/package/DesktopLauncher.dmg
        appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}   # e.g. foo@example.com
        appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}   # e.g. app-specific password
        primary-bundle-id: my.app.package
        verbose: true
```
